version: '2.2'

services:
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: 'citusdata/citus:9.2.1'
    ports: ["${MASTER_EXTERNAL_PORT:-5432}:5432"]
    labels: ['com.citusdata.role=Master']
  worker:
    image: 'citusdata/citus:9.2.1'
    labels: ['com.citusdata.role=Worker']
    depends_on: { manager: { condition: service_healthy } }
    scale: 3
  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: 'citusdata/membership-manager:0.2.0'
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    depends_on: { master: { condition: service_healthy } }
  ds:
    container_name: ds
    image: '${COMPANY_NAME:-onlyoffice}/${DS_CONTAINER_NAME:-"documentserver-ie:latest"}'
    ports: 
      - '80:80'
    environment:
      - DB_HOST=master
      - DB_NAME=postgres
      - DB_USER=postgres
    stdin_open: true
    depends_on: 
      - 'master'
